### ISSUE TITLE
Planner::plane returning value

### ISSUE THREAD

**Issue by lyris85** [cvra/goap-cpp#1]
Planner::plane can return values higher than max_path_len, instead of returning -1 in case no path is found within max_path_len attempt.

Example:

state = 0
goal = 100
action = state++

max_path_len = 10
path[max_path_len]
len = planner.plan(state, goal, action.data(), action.size(), path, max_path_len);

This will return len = 100 instead of -1

**Comment by antoinealb** [comment]
Good catch, thanks for the report. I fixed it and added a test for that case in 5513e28f563e5970a04c16322f70a5fc965f6e6d.
